CREATE TABLE boston_crime (
  INCIDENT_NUMBER VARCHAR(100) NOT NULL,
   OFFENSE_CODE  INT NOT NULL,
   OFFENSE_CODE_GROUP  VARCHAR (255) NOT NULL,
   OFFENSE_DESCRIPTION VARCHAR (255) NOT NULL, 
   DISTRICT VARCHAR (255) NOT NULL,
   REPORTING_AREA INT NOT NULL, SHOOTING  VARCHAR(2),
   OCCURRED_ON_DATE TIMESTAMP, YEAR INT NOT NULL,
   MONTH INT NOT NULL, DAY_OF_WEEK VARCHAR (255),
   HOUR INT NOT NULL, UCR_PART VARCHAR (255),
   STREET VARCHAR (255), Lat numeric,
   Long numeric, Location VARCHAR(255) NOT NULL);